id: IE5854949
legacy_id: P009103
ocr_import_info:
  bdrc_scan_id: W1CZ1085
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T22:18:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:50:02.132916+00:00'
last_modified: 2022-08-31 02:50:18.587281
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1085
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1085
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོར་དབྱིངས་དཀྱིལ་འཁོར་གྱི་དཀའ་འགྲེལ་མདོར་བསྡུས།
statistics:
  ocr_word_mean_confidence_index: 0.5032835534941044
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I1CZ1461:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1461
      total_pages: 114
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1461.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5032835534941044
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
