id: P009103
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 19:23:04.629997
source_metadata:
  id: bdr:W1CZ1085
  title: རྡོར་དབྱིངས་དཀྱིལ་འཁོར་གྱི་དཀའ་འགྲེལ་མདོར་བསྡུས
  author: ''
  volumes:
    2ce27b1f2c974fa98606ecfddbb76b0e:
      image_group_id: I1CZ1461
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
